default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "baseapp" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "baseapp_production" } %>
